name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Python tools
        run: pip install black flake8
      - name: Run Black
        run: black --check .
      - name: Run Flake8
        run: flake8 .

  rust-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run rustfmt
        run: cargo fmt -- --check
      - name: Run clippy
        run: cargo clippy -- -D warnings

  elixir-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15'
          otp-version: '26'
      - name: Run mix format check
        run: mix format --check-formatted

  config-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install YAML and TOML linters
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
          curl -s https://packagecloud.io/install/repositories/tamasfe/taplo/script.deb.sh | sudo bash
          sudo apt-get install -y taplo-cli
      - name: Lint YAML files
        run: yamllint .
      - name: Lint TOML files
        run: taplo check
