name: Config Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  config-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('tools/requirements-config.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install yamllint
        run: pip install -r tools/requirements-config.txt

      - name: Install Taplo CLI
        run: |
          curl -L -o taplo.gz https://github.com/tamasfe/taplo/releases/download/0.10.0/taplo-linux-x86_64.gz
          gunzip taplo.gz
          chmod +x taplo
          sudo mv taplo /usr/local/bin/taplo

      - name: Lint YAML files
        run: yamllint -c tools/.yamllint .

      - name: Lint TOML files
        run: taplo fmt --check
