name: Rust Lint

on:
  push:
    branches: [main]
    paths:
      - 'rust/**'
  pull_request:
    branches: [main]
    paths:
      - 'rust/**'

jobs:
  rust-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.88.0
          override: true

      - name: Run cargo fmt
        run: cargo fmt -- --check

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
