name: YAML and TOML Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  yaml-toml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('tools/requirements-yamllint.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install yamllint
        run: pip install -r tools/requirements-yamllint.txt

      - name: Install Taplo CLI
        uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli@0.10.0

      - name: Lint YAML files
        run: yamllint -c tools/.yamllint .

      - name: Lint TOML files
        run: taplo fmt --check --diff
